### ISSUE TITLE
Php dependency

### ISSUE THREAD

**Issue by agiuliano** [PUGX/Bindto#3]
I noticed that bindto depends on  `"phpunit/phpunit": "^5.0@dev",` wich in turn depends on `php 5.6` whereas binddto declares to depend on `php >= 5.5`
Which php version win? 
Do we have to upgrade the php requirements or downgrade the phpunit dependency?

**Comment by liuggio** [comment]
ops yes you are right,
I think this is a composer bug, it didn't realize during "composer require phpunit" the php constrain,
BTW please can you do a PR with che correct phpunit version?

**Comment by agiuliano** [comment]
of course, here it is #4

**Comment by liuggio** [comment]
thanks boss-
